# Full-scale hierarchical model configuration
# Predicts all 6 taxonomic levels

experiment:
  union_type: "standard"  # a+b+d
  fold_type: "exp1_sequence_fold"
  dataset_size: "full_10fold"
  num_folds: 10

model:
  type: "bert"
  hidden_size: 512
  num_hidden_layers: 10
  num_attention_heads: 8
  intermediate_size: 2048
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  max_position_embeddings: 502
  
  # Hierarchical classification settings
  classification_type: "hierarchical"
  hierarchical_dropout: 0.1 
  taxonomic_levels: ["phylum", "class", "order", "family", "genus", "species"]
  use_uncertainty_weighting: false
  l1_lambda: 0

preprocessing:
  tokenizer: "kmer"
  kmer_size: 3
  stride: 3
  max_length: 1500
  padding: "max_length"
  truncation: true
  base_modification_probability: 0.01
  alphabet: ["A","C","G","T"]

training:
  batch_size: 284
  learning_rate: 0.0001
  weight_decay: 0.01
  warmup_steps: 350
  max_epochs: 15
  
  patience: 20
  min_delta: 0.001
  monitor: "val_accuracy"
  
  save_best_only: true
  save_frequency: 1
  
  device: "cuda"
  num_workers: 4
  mixed_precision: true
  
  log_frequency: 100
  verbose: true

seed: 42