# Tiny single species model for conservative union

experiment:
  union_type: "conservative"  # a+b+c (conservative)
  fold_type: "exp1_sequence_fold"
  dataset_size: "debug_5genera_10fold"
  num_folds: 10
  folds_to_train: [1]

model:
  type: "bert"
  vocab_size: 256
  hidden_size: 64
  num_hidden_layers: 2
  num_attention_heads: 2
  intermediate_size: 256
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  max_position_embeddings: 128
  
  # Single-rank classification settings
  classification_type: "single"
  taxonomic_levels: ["species"]  # Only predict species

preprocessing:
  tokenizer: "kmer"
  kmer_size: 3
  stride: 1
  max_length: 128
  padding: "max_length"
  truncation: true

training:
  batch_size: 16
  learning_rate: 0.00005
  weight_decay: 0.01
  warmup_steps: 10
  max_epochs: 15
  
  patience: 0
  min_delta: 0.001
  monitor: "val_accuracy"
  
  save_best_only: true
  save_frequency: 1
  
  device: "cuda"
  num_workers: 0
  mixed_precision: false
  
  log_frequency: 10
  verbose: true

seed: 42